<?php

namespace VVM\CyclovoyageurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArretRepository extends EntityRepository
{
}
