photo:
    path:     /
    defaults: { _controller: "VVMCyclovoyageurBundle:Photo:index" }

photo_show:
    path:     /{id}/show
    defaults: { _controller: "VVMCyclovoyageurBundle:Photo:show" }

photo_new:
    path:     /new
    defaults: { _controller: "VVMCyclovoyageurBundle:Photo:new" }

photo_create:
    path:     /create
    defaults: { _controller: "VVMCyclovoyageurBundle:Photo:create" }
    requirements: { _method: post }

photo_edit:
    path:     /{id}/edit
    defaults: { _controller: "VVMCyclovoyageurBundle:Photo:edit" }

photo_update:
    path:     /{id}/update
    defaults: { _controller: "VVMCyclovoyageurBundle:Photo:update" }
    requirements: { _method: post|put }

photo_delete:
    path:     /{id}/delete
    defaults: { _controller: "VVMCyclovoyageurBundle:Photo:delete" }
    requirements: { _method: post|delete }
