voyage:
    path:     /
    defaults: { _controller: "VVMCyclovoyageurBundle:Voyage:index" }

voyage_show:
    path:     /{id}/show
    defaults: { _controller: "VVMCyclovoyageurBundle:Voyage:show" }

voyage_new:
    path:     /new
    defaults: { _controller: "VVMCyclovoyageurBundle:Voyage:new" }

voyage_create:
    path:     /create
    defaults: { _controller: "VVMCyclovoyageurBundle:Voyage:create" }
    requirements: { _method: post }

voyage_edit:
    path:     /{id}/edit
    defaults: { _controller: "VVMCyclovoyageurBundle:Voyage:edit" }

voyage_update:
    path:     /{id}/update
    defaults: { _controller: "VVMCyclovoyageurBundle:Voyage:update" }
    requirements: { _method: post|put }

voyage_delete:
    path:     /{id}/delete
    defaults: { _controller: "VVMCyclovoyageurBundle:Voyage:delete" }
    requirements: { _method: post|delete }
