services:
#    vvm_user.example:
#        class: VVM\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


parameters:
    roles:
        ROLE_FRIEND: Invité
        ROLE_USER: Utilisateur
        ROLE_ADMIN: Administrateur


services:
    vvm_user.registration.form.type:
        class: VVM\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%,%roles%]
        tags:
            - { name: form.type, alias: vvm_user_registration }